[ADMINAPI-699] Separate execution from e2e
Ed-Fi-Alliance-OSS/AdminAPI-2.0 pull request #43
Opened 2023-08-17 20:25 UTC by jpardogrowthaccelerationpartners

@jasonh-edfi @CSR2017 @jagudelo-gap @lchavarriaga 
You can review and merge this PR
- Separation of E2E tests in different collections
- Skip sending results to Jira

2023-08-18 20:45 UTC, jagudelo-gap requested changes

2023-08-18 22:16 UTC, jpardogrowthaccelerationpartners commented on Application/EdFi.Ods.AdminApi/E2E Tests/Admin API E2E 2.0 - Actions.postman_collection.json
> +	"variable": [
fixed, I update all collections with just the parameters you use and each one

2023-08-18 22:18 UTC, jpardogrowthaccelerationpartners commented on Application/EdFi.Ods.AdminApi/E2E Tests/Admin API E2E 2.0 - Application.postman_collection.json
> +			"name": "Landing",
Fixed, I already removed the landing and user management folders, now everything is generated in the pre-request

2023-08-22 15:07 UTC, jagudelo-gap approved these changes

2023-08-22 15:31 UTC, lchavarriaga approved these changes

2023-08-23 14:56 UTC, CSR2017 approved these changes
Changes look good.

2023-08-23 15:02 UTC, merged